# Generated by Django 3.1.3 on 2020-11-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotaedu', '0002_auto_20201105_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_image',
            field=models.ImageField(default=0, upload_to='img'),
            preserve_default=False,
        ),
    ]
